# These are supported funding model platforms

github: [blackXmask]            # GitHub Sponsors username
patreon: blackxmask             # Patreon username
open_collective: blackxmask     # Open Collective slug

